# Generated by Django 2.1.3 on 2018-11-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_json', models.TextField()),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
